In [1]:
from google.colab import files
uploaded = files.upload()

Saving TCS_Infosys_2021_2025_Combined.xlsx.xlsx to TCS_Infosys_2021_2025_Combined.xlsx.xlsx

In [2]:
import pandas as pd
df = pd.read_excel('TCS_Infosys_2021_2025_Combined.xlsx.xlsx')
print("Excel loaded successfully!")

Excel loaded successfully!

In [3]:
df.head()

        Date  Company    Price    Open     High      Low   Vol.  Change %
0 2021-01-01      TCS  2928.25  2880.0  2940.00  2879.00  2.68M    0.0229
1 2021-01-01  Infosys  1260.45  1257.9  1265.50  1255.80  4.25M    0.0037
2 2021-01-04      TCS  3039.45  2950.0  3050.75  2940.95  5.11M    0.0380
3 2021-01-04  Infosys  1288.25  1269.0  1290.00  1261.15  7.21M    0.0221
4 2021-01-05      TCS  3093.00  3039.6  3114.25  3039.60  5.80M    0.0176

In [6]:
import sqlite3

conn = sqlite3.connect('stock_analysis.db')

print("SQL connection created successfully!")

SQL connection created successfully!

In [7]:
df.to_sql(
    'stock_data',
    conn,
    if_exists='replace',
    index=False
)

print("stock_data table created successfully!")

stock_data table created successfully!

In [8]:
query = """
SELECT *
FROM stock_data
LIMIT 5;
"""

pd.read_sql_query(query, conn)

,Date,Company,Price,Open,High,Low,Vol.,Change %
0,2021-01-01 00:00:00,TCS,2928.25,2880.0,2940.00,2879.00,2.68M,0.0229
1,2021-01-01 00:00:00,Infosys,1260.45,1257.9,1265.50,1255.80,4.25M,0.0037
2,2021-01-04 00:00:00,TCS,3039.45,2950.0,3050.75,2940.95,5.11M,0.0380
3,2021-01-04 00:00:00,Infosys,1288.25,1269.0,1290.00,1261.15,7.21M,0.0221
4,2021-01-05 00:00:00,TCS,3093.00,3039.6,3114.25,3039.60,5.80M,0.0176

In [9]:
query = """
SELECT COUNT(*) AS Total_Records
FROM stock_data;
"""

pd.read_sql_query(query, conn)

   Total_Records
0           2480

In [10]:
query = """
SELECT
    Company,
    COUNT(*) AS Total_Records
FROM stock_data
GROUP BY Company;
"""

pd.read_sql_query(query, conn)

   Company  Total_Records
0  Infosys           1240
1      TCS           1240

In [11]:
query = """
SELECT
    Company,
    ROUND(AVG(Price), 2) AS Average_Price
FROM stock_data
GROUP BY Company;
"""

pd.read_sql_query(query, conn)

   Company  Average_Price
0  Infosys        1566.45
1      TCS        3511.97

In [12]:
query = """
SELECT
    Company,
    MAX(Price) AS Highest_Price,
    MIN(Price) AS Lowest_Price
FROM stock_data
GROUP BY Company;
"""

pd.read_sql_query(query, conn)

   Company  Highest_Price  Lowest_Price
0  Infosys        1999.70       1216.54
1      TCS        4553.75       2888.40

In [14]:
query = """
SELECT
    Company,
    ROUND(MAX(Price), 2) AS Highest_Price,
    ROUND(MIN(Price), 2) AS Lowest_Price
FROM stock_data
GROUP BY Company;
"""

pd.read_sql_query(query, conn)

   Company  Highest_Price  Lowest_Price
0  Infosys        1999.70       1216.54
1      TCS        4553.75       2888.40

In [18]:
pd.read_sql_query("PRAGMA table_info(stock_data);", conn)

   cid      name       type  notnull dflt_value  pk
0    0      Date  TIMESTAMP        0       None   0
1    1   Company       TEXT        0       None   0
2    2     Price       REAL        0       None   0
3    3      Open       REAL        0       None   0
4    4      High       REAL        0       None   0
5    5       Low       REAL        0       None   0
6    6      Vol.       TEXT        0       None   0
7    7  Change %       REAL        0       None   0

In [19]:
query = """
SELECT
    Company,
    ROUND(AVG(`Change %`), 4) AS Average_Change_Percent
FROM stock_data
GROUP BY Company;
"""

pd.read_sql_query(query, conn)

   Company  Average_Change_Percent
0  Infosys                  0.0003
1      TCS                  0.0002

In [20]:
query = """
SELECT
    Company,
    strftime('%Y', Date) AS Year,
    ROUND(AVG(Price), 2) AS Average_Price
FROM stock_data
GROUP BY Company, Year
ORDER BY Company, Year;
"""

pd.read_sql_query(query, conn)

   Company  Year  Average_Price
0  Infosys  2021        1535.50
1  Infosys  2022        1587.26
2  Infosys  2023        1408.58
3  Infosys  2024        1700.74
4  Infosys  2025        1598.23
5      TCS  2021        3353.85
6      TCS  2022        3355.16
7      TCS  2023        3372.14
8      TCS  2024        4089.15
9      TCS  2025        3386.60

In [24]:
query = """
SELECT
    Company,
    strftime('%Y', Date) AS Year,
    ROUND(MAX(Price), 2) AS Maximum_Price
FROM stock_data
GROUP BY Company, Year
ORDER BY Company, Year;
"""

pd.read_sql_query(query, conn)

   Company  Year  Maximum_Price
0  Infosys  2021        1892.85
1  Infosys  2022        1939.50
2  Infosys  2023        1607.94
3  Infosys  2024        1999.70
4  Infosys  2025        1966.95
5      TCS  2021        3954.55
6      TCS  2022        4019.15
7      TCS  2023        3843.19
8      TCS  2024        4553.75
9      TCS  2025        4223.77

In [26]:
pd.read_sql_query("PRAGMA table_info(stock_data);", conn)

   cid      name       type  notnull dflt_value  pk
0    0      Date  TIMESTAMP        0       None   0
1    1   Company       TEXT        0       None   0
2    2     Price       REAL        0       None   0
3    3      Open       REAL        0       None   0
4    4      High       REAL        0       None   0
5    5       Low       REAL        0       None   0
6    6      Vol.       TEXT        0       None   0
7    7  Change %       REAL        0       None   0

In [28]:
query = """
SELECT
    Date,
    Company,
    Price,
    `Change %` AS Change_Percent
FROM stock_data
ORDER BY `Change %` DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

                  Date  Company    Price  Change_Percent
0  2024-01-12 00:00:00  Infosys  1603.71          0.0793
1  2025-05-12 00:00:00  Infosys  1626.90          0.0791
2  2024-07-12 00:00:00      TCS  4183.95          0.0663
3  2023-12-15 00:00:00      TCS  3843.19          0.0528
4  2025-05-12 00:00:00      TCS  3620.40          0.0524
5  2023-07-14 00:00:00      TCS  3498.44          0.0521
6  2023-12-15 00:00:00  Infosys  1569.56          0.0513
7  2025-09-09 00:00:00  Infosys  1504.30          0.0498
8  2021-01-11 00:00:00  Infosys  1376.20          0.0489
9  2022-11-11 00:00:00  Infosys  1561.30          0.0454

In [29]:
query = """
SELECT
    Date,
    Company,
    Price,
    `Change %` AS Change_Percent
FROM stock_data
ORDER BY `Change %` ASC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

                  Date  Company    Price  Change_Percent
0  2023-04-17 00:00:00  Infosys  1251.25         -0.0942
1  2023-07-21 00:00:00  Infosys  1324.14         -0.0813
2  2022-04-18 00:00:00  Infosys  1621.40         -0.0727
3  2021-10-11 00:00:00      TCS  3685.60         -0.0635
4  2025-01-17 00:00:00  Infosys  1815.45         -0.0586
5  2022-05-19 00:00:00  Infosys  1419.15         -0.0544
6  2022-05-19 00:00:00      TCS  3261.95         -0.0542
7  2022-07-11 00:00:00      TCS  3037.90         -0.0464
8  2022-02-24 00:00:00      TCS  3401.65         -0.0455
9  2022-09-14 00:00:00  Infosys  1467.13         -0.0450

In [30]:
query = """
SELECT
    Company,
    Date,
    Price,
    `Change %` AS Change_Percent
FROM stock_data
WHERE `Change %` = (
    SELECT MAX(s2.`Change %`)
    FROM stock_data s2
    WHERE s2.Company = stock_data.Company
)
ORDER BY Company;
"""

pd.read_sql_query(query, conn)

   Company                 Date    Price  Change_Percent
0  Infosys  2024-01-12 00:00:00  1603.71          0.0793
1      TCS  2024-07-12 00:00:00  4183.95          0.0663

In [31]:
query = """
SELECT
    Company,
    Date,
    Price,
    `Change %` AS Change_Percent
FROM stock_data
WHERE `Change %` = (
    SELECT MIN(s2.`Change %`)
    FROM stock_data s2
    WHERE s2.Company = stock_data.Company
)
ORDER BY Company;
"""

pd.read_sql_query(query, conn)

   Company                 Date    Price  Change_Percent
0  Infosys  2023-04-17 00:00:00  1251.25         -0.0942
1      TCS  2021-10-11 00:00:00  3685.60         -0.0635

In [33]:
pd.read_sql_query("PRAGMA table_info(stock_data);", conn)

   cid      name       type  notnull dflt_value  pk
0    0      Date  TIMESTAMP        0       None   0
1    1   Company       TEXT        0       None   0
2    2     Price       REAL        0       None   0
3    3      Open       REAL        0       None   0
4    4      High       REAL        0       None   0
5    5       Low       REAL        0       None   0
6    6      Vol.       TEXT        0       None   0
7    7  Change %       REAL        0       None   0

In [34]:
query = """
SELECT
    Company,
    COUNT(*) AS Total_Records,
    ROUND(AVG(Price), 2) AS Average_Price,
    ROUND(MAX(Price), 2) AS Highest_Price,
    ROUND(MIN(Price), 2) AS Lowest_Price,
    SUM(CAST(REPLACE(`Vol.`, ',', '') AS REAL)) AS Total_Volume,
    ROUND(AVG(`Change %`), 4) AS Average_Change_Percent
FROM stock_data
GROUP BY Company
ORDER BY Company;
"""

final_sql_summary = pd.read_sql_query(query, conn)

final_sql_summary

,Company,Total_Records,Average_Price,Highest_Price,Lowest_Price,Total_Volume,Average_Change_Percent
0,Infosys,1240,1566.45,1999.70,1216.54,11548.52,0.0003
1,TCS,1240,3511.97,4553.75,2888.40,26906.48,0.0002

In [35]:
final_sql_summary.to_excel(
    'SQL_Final_Summary.xlsx',
    index=False
)

print("SQL Final Summary saved successfully!")

SQL Final Summary saved successfully!